### ISSUE TITLE
Failure while fetching WebIcon

### ISSUE THREAD

**Issue by mark-kowalski** [wahni/reviews-to-slack#10]
I am getting a error when the module tries to fetch the WebIcon of my app. Easy solution would be to check if variable webpIcon is not null. Are you willing to fix this or should i create a PullRequest for that?

```
TypeError: Cannot read property 'startsWith' of undefined
    at Request._callback (/Users/kowalma/repo/dev-ops/reviewBot/node_modules/reviews-to-slack/index.js:150:21)
    at Request.self.callback (/Users/kowalma/repo/dev-ops/reviewBot/node_modules/reviews-to-slack/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/Users/kowalma/repo/dev-ops/reviewBot/node_modules/reviews-to-slack/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/Users/kowalma/repo/dev-ops/reviewBot/node_modules/reviews-to-slack/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

```
reviews-to-slack/index.js:150
      if (!webpIcon.startsWith('http')) {
                    ^
```

**Comment by wahni** [comment]
@mark-kowalski Thanks for reporting. It looks like the Google Play app page structure was changed, neither `id-app-title` or `cover-image` classes are defined anymore. I can have a fix up in a few hours. Will also make it handle missing elements more gracefully..
